---
title: "vis-proy"
format: html
editor: visual
---

```{r}
setwd(".")

list.of.packages <- c("sf", "plotly", "tidyverse", "rnaturalearth", "rnaturalearthhires", "readr", "crosstalk", "stringdist", "mapSpain", "viridis", "shiny","forecast")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(list.of.packages, require, character.only=TRUE)
```

```{r}
turismo_receptor <- read_delim(
  "data/turismo_receptor_provincia_pais copy.csv",
  delim = ";",
  locale = locale(decimal_mark = ",", encoding = "ISO-8859-1"),
  col_types = cols(
    AÑO = col_double(),
    MES = col_double(),
    TURISTAS = col_double(),
    ESTANCIA_MEDIA = col_double(),
    PROVINCIA_DESTINO = col_character(),
    CONTINENTE_ORIGEN = col_character(),
    PAIS_ORIGEN = col_character(),
    PERNOCTACIONES = col_double()
  )
)|>
  filter(!grepl("Total", PROVINCIA_DESTINO, ignore.case = TRUE))
```

```{r}
turismo_receptor
```

```{r}
turismo_receptor <- turismo_receptor |> 
  filter(!grepl("^Total", PAIS_ORIGEN))
```

```{r}
c <- setdiff(paises, world$name_es)
distance_matrix <- stringdistmatrix(c, world$name_es, method = "jw")

closest_matches <- apply(distance_matrix, 1, function(row) {
  world$name_es[which.min(row)]
})


matches <- data.frame(
  Original = c,
  Match = closest_matches
)
print(matches)

```

```{r}
threshold <- 0.15
matches <- data.frame(
  Original = c,
  Match = apply(distance_matrix, 1, function(row) {
    if (min(row) <= threshold) world$name_es[which.min(row)] else NA
  })
)


matches <- matches[!is.na(matches$Match), ]


print(matches)
```

```{r}

methods <- c("lv", "dl", "jw", "qgram", "cosine", "jaccard")
results <- sapply(methods, function(m) {
  sapply(c, function(x) {
    world$name_es[which.min(stringdist(x, world$name_es, method = m))]
  })
})


colnames(results) <- methods
results
```

```{r}
range(world$label_x)
range(world$label_y)  
```

```{r}
world |> 
  mutate(geometry = st_make_valid(geometry)) |> 
  select(geometry) |> 
  mutate(centroid = st_centroid(geometry))
```

```{r}

df |> 
  left_join(world, by = c("PAIS_DESTINO" = "name_es"))
```

```{r}
g <- list(
  projection = list(type = 'equirectangular'),
  showland = TRUE,
  landcolor = toRGB("gray95"),
  countrycolor = toRGB("gray80")
)



world <- ne_countries(returnclass = "sf")
spain <- ne_states(country = "Spain", returnclass = "sf")

plot_geo(world) |> 
  add_markers(x=~label_x, y=~label_y)
```

```{r}
w <- highlight_key(world, key=~name)
widgets <- bscols(
  widths = c(12),
  filter_select("country", "Country", w,~name)
)

bscols(
  widths = c(4,8), widgets,
  plot_geo() |> 
  add_markers(
    data = w,
    x = ~label_x,
    y = ~label_y,
    text = ~name,
    marker = list(size = 6, color = "blue"),
    hoverinfo = "text"
  ) |> 
  layout(
    geo = g
)
)
```

## Gráficos

```{r}
turismo_receptor$MES_COD <- factor(turismo_receptor$MES, 
                               levels = 1:12, 
                               labels = c("Ene", "Feb", "Mar", "Abr", "May", "Jun", 
                                          "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"))

```

```{r}

fig <- turismo_receptor %>%
  filter(AÑO == 2023, PROVINCIA_DESTINO=="Madrid") |>
  plot_ly(
    x = ~ESTANCIA_MEDIA,
    y = ~MES_COD,
    split = ~MES_COD,
    type = 'violin',
    orientation = "h",
    text = ~paste("Estancia Media: ", ESTANCIA_MEDIA, "<br>País de Origen: ", PAIS_ORIGEN),
    hoverinfo = "text",
    box = list(
      visible = T
    ),
    meanline = list(
      visible = T
    )
  ) 

fig <- fig %>%
  layout(
    xaxis = list(
      title = "Estancia Media"
    ),
    yaxis = list(
      title = "Mes",
      categoryorder = "array",
      categoryarray = rev(c("Ene", "Feb", "Mar", "Abr", "May", "Jun", 
                        "Jul", "Ago", "Sep", "Oct", "Nov", "Dic")),
      zeroline = FALSE
    )
  ) |> hide_legend()

fig

```

```{r}

hex_prov <- esp_get_hex_prov() |>
  rename(PROVINCIA_DESTINO = ine.prov.name) |>
  select(PROVINCIA_DESTINO, label, codauto, nuts2.name, geom)


hex_prov_coords <- hex_prov$geom |> st_centroid() |> st_coordinates()
hex_prov$X <- hex_prov_coords[, 1]
hex_prov$Y <- hex_prov_coords[, 2]

tur_total_year <- turismo_receptor |>
                  group_by(AÑO, PROVINCIA_DESTINO) |>
                  summarise(m=sum(TURISTAS))

completo <- merge(tur_total_year, hex_prov, by = "PROVINCIA_DESTINO") |>
  st_as_sf()


```

```{r}
completo_filtrado <- completo %>%
  filter(AÑO == 2023) %>%
  mutate(rango_turistas = cut(
    m,
    breaks = c(0, 6e6, 9e6, 12e6, 15e6, Inf),
    labels = c("0-6M", "6-9M", "9-12M", "12-15M", "15M+"),
    include.lowest = TRUE
  ))


```

```{r}
plot_ly(source = "hexmap_source", data = completo) |>
  filter(AÑO == 2023) |>  # Filtrar por año seleccionado en Shiny
  add_sf(
    split = ~NULL, # Para que no salga la leyenda por provincias
    color = ~cut(m, 
                 breaks = c(0, 5e5, 1e6, 5e6, 10e6, Inf),
                 labels = c("0k-5k", "5k-1M", "1M-5M", "5M-10M", "10M+")),
    colors = c("#FFEDA0", "#FEB24C", "#FD8D3C", "#FC4E2A", "#E31A1C"), # Colores específicos
    hoveron = "fills",
    hovertext = ~paste("Provincia:", PROVINCIA_DESTINO, "<br>Turistas:", format(m, big.mark = ",")),
    showlegend = TRUE
  ) |>
  add_text(
    data = hex_prov,
    x = ~X,
    y = ~Y,
    text = ~label,
    textfont = list(size = 10, color = "black"),
    showlegend = FALSE
  ) |>
  layout(
    title = list(
      text = paste("Mapa Hexagonal de España - Año", 2023),
      xanchor = "center",
      font = list(size = 20)
    ),
      
    hovermode = "closest",
    legend = list(
      orientation = "h",        # Leyenda en orientación horizontal
      xanchor = "center",       # Centrar la leyenda
      x = 0.5,                  # Posición horizontal
      y = 1.1,
      font = list(size = 8)
    ),
    margin = list(t = 80) # Ajustar el margen superior para la leyenda
  )
```

```{r}
top5 <- df |> 
        group_by(AÑO, PROVINCIA_DESTINO, PAIS_ORIGEN) |>
        summarise(m=sum(TURISTAS, na.rm=TRUE)) |>
        arrange(desc(m)) |>
        top_n(5)


```

```{r}
datos <- data.frame(
  pais = c("USA", "China", "India", "Russia", "Spain", "Brazil", "UK", "France", "Italy"),
  valor = c(149300000, 140371452, 106950055, 80377636, 56329242, 51719147, 42860928, 36626686, 34282663),
  bandera_url = c(
    "https://flagcdn.com/us.svg",
    "https://flagcdn.com/cn.svg",
    "https://flagcdn.com/in.svg",
    "https://flagcdn.com/ru.svg",
    "https://flagcdn.com/es.svg",
    "https://flagcdn.com/br.svg",
    "https://flagcdn.com/gb.svg",
    "https://flagcdn.com/fr.svg",
    "https://flagcdn.com/it.svg"
  )
)


grafico <- plot_ly(
  data = datos,
  x = ~valor,
  y = ~reorder(pais, valor),
  type = 'bar',
  orientation = 'h',
  marker = list(color = 'rgba(100, 200, 255, 0.7)'),
  text = ~scales::comma(valor), 
  textposition = 'auto'
)

imagenes <- lapply(seq_len(nrow(datos)), function(i) {
  list(
    source = datos$bandera_url[i],
    xref = "x", yref = "y",
    x = datos$valor[i] + max(datos$valor) * 0.06,
    y = datos$pais[i],
    sizex = max(datos$valor) * 0.06,
    sizey = 1,
    xanchor = "left", yanchor = "middle",
    layer = "above"
  )
})


grafico <- grafico |>
  layout(
    title = "Plantilla barras",
    xaxis = list(
      title = "",
      showgrid = FALSE,
      range = c(0, max(datos$valor) * 1.2)
    ),
    yaxis = list(title = "", showgrid = FALSE),
    images = imagenes,
    annotations = list(text = "AÑO", 
                       x = 1,
                       y = 0,
                       xref = "paper", 
                       yref = "paper",
                       showarrow = FALSE, 
                       font = list(size = 100,color = "lightgray"))
  )

grafico
```

Con nuestros datos

```{r}
aggregate_turismo_receptor <- turismo_receptor |>
                              group_by(AÑO, PROVINCIA_DESTINO) |>
                              summarise(m=sum(TURISTAS))
                              
```

```{r}
hex_prov <- esp_get_hex_prov() |>
            rename(PROVINCIA_DESTINO=ine.prov.name) |>
            select(PROVINCIA_DESTINO, label, codauto, nuts2.name)



hex_prov_coords <- hex_prov$geom |> st_centroid() |> st_coordinates()
hex_prov$X <- hex_prov_coords[, 1]
hex_prov$Y <- hex_prov_coords[, 2]


completo <- merge(aggregate_turismo_receptor, hex_prov, by="PROVINCIA_DESTINO") |> st_as_sf() 

env <- completo |> highlight_key(~PROVINCIA_DESTINO)

p <- completo
  plot_ly() |>
  group_by(PROVINCIA_DESTINO) |>
  add_sf(
    data = completo,
    split = ~PROVINCIA_DESTINO,
    hoveron = "fills",
    hovertext = ~PROVINCIA_DESTINO,
    line = list(width = 0.5, color = 'black')
  ) |>
  add_text(
    data = hex_prov,
    x = ~X,
    y = ~Y,
    text = ~PROVINCIA_DESTINO,
    textfont = list(size = 7, color = "black"),
    showlegend = FALSE
  ) |>
  layout(
    title = "Plantilla mapa"
  ) |>
  hide_legend() |>
  highlight(on="plotly_click", selectize = TRUE)

p
```

```{r}
ocup <- read_csv("data/ocupacion.csv")
```

```{r}
ocup
```

```{r}

df <- ocup %>%
  filter(LUGAR_RESIDENCIA == "Total", PROVINCIA %in% c("Valencia")) %>%
  mutate(date = AÑO + (MES - 1) / 12) |>
  select(date, VIAJEROS, PROVINCIA)


accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}


df <- df %>% accumulate_by(~date)


fig <- df %>%
  plot_ly(
    x = ~date, 
    y = ~VIAJEROS,
    frame = ~frame, 
    type = 'scatter',
    mode = 'lines',
    line = list(simplify = F)
  )

fig <- fig %>% layout(
  title = "Evolución de Viajeros en Álava",
  xaxis = list(title = "Fecha (Año Decimal)", zeroline = TRUE, range=c(1999, 2024)),
  yaxis = list(title = "Viajeros", zeroline = TRUE, range=c(0, 500000))
)

# Configuración de la animación
#fig <- fig %>% animation_opts(
#  frame = 50, 
#  transition = 0, 
#  redraw = FALSE
#)
#fig <- fig %>% animation_slider(
#  hide = T
#)
#fig <- fig %>% animation_button(
#  x = 1, xanchor = "right", y = 0, yanchor = "bottom"
#)

subplot(fig,fig) |>
  hide_legend()|>
  animation_opts(
   frame = 50, 
   transition = 0, 
redraw = FALSE
) 

```

```{r}

o <- ocup |> mutate(date = AÑO + (MES - 1) / 12) |>
        filter(LUGAR_RESIDENCIA != "Total")|>
        filter(AÑO > 2010)
       # filter(PROVINCIA %in% c("Albacete", "Alicante", "Almería")) |>
  
p1 <- o |>
  filter(LUGAR_RESIDENCIA == "Residentes en España") |>
  plot_ly(x = ~PERSONAL_EMPLEADO, y = ~GRADO_OCUPA_PLAZAS, size = ~VIAJEROS) |>
 add_markers(frame = ~date, ids = ~PROVINCIA) |>
  layout(
    xaxis=list(
      range=c(0, 1e5),
      title="Hola"
    )
  )

p2 <- o |>
  filter(LUGAR_RESIDENCIA == "Residentes en el Extranjero") |>
  plot_ly(x = ~PERSONAL_EMPLEADO, y = ~GRADO_OCUPA_PLAZAS, size = ~VIAJEROS)|>
  add_markers(frame = ~date, ids = ~PROVINCIA, text = ~PROVINCIA, hoverinfo="text") |>
  layout(
    xaxis=list(
      range=c(0, 1e5)
    )
  )
  
subplot(p1,p2, shareY = T, titleX = T) |>
animation_opts(500, easing = "linear", redraw =T) %>%
animation_button( x = 1, xanchor = "right", y = 0, yanchor = "bottom") %>%
animation_slider(currentvalue = list(prefix = "YEAR ", font = list(color="red")))
```

```{r}
source("server/data_transformations.R")
```

```{r}
source("server/data_transformations.R")
```

```{r}
provincias <- c("Madrid", "Barcelona", "Girona")

rank <- turismo_receptor |>
            get_ranking_provinces(provincias) |>
            create_inverted_ranking()



```

```{r}
data <- rank
```

```{r}

data_highlight <- highlight_key(data, key = ~Province)

p <- plot_ly(data_highlight)

p <- p %>%
  group_by(Province) %>%
  add_lines(
    x = ~Year,
    y = ~Position,
    name = ~Province,
    mode = "lines+markers",
    marker = list(size = 10),
    text = ~Province
  )


annotations <- list()

for (provincia in unique(data$Province)) {
  data_provincia <- data %>% filter(Province == provincia)
  
  annotations <- append(annotations, list(
    list(
      x = min(data_provincia$Year) - 0.5,
      y = data_provincia$Position[data_provincia$Year == min(data_provincia$Year)],
      text = provincia,
      showarrow = FALSE,
      xanchor = "right",
      font = list(size = 12)
    )
  ))
  
  annotations <- append(annotations, list(
    list(
      x = max(data_provincia$Year) + 0.5, # Margen extra
      y = data_provincia$Position[data_provincia$Year == max(data_provincia$Year)],
      text = provincia,
      showarrow = FALSE,
      xanchor = "left",
      font = list(size = 12)
    )
  ))
}

p <- layout(
  p,
  title = "Chupapinga",
  xaxis = list(
    title = "",
    showgrid = FALSE,
    tickvals = unique(data$Year)
  ),
  yaxis = list(
    showgrid = FALSE,
    showticklabels = FALSE,
    title = ""
  ),
  legend = list(
    title = list(text = "Provincias")
  ),
  annotations = annotations,
  autosize = FALSE,
  width = 800,
  height = 400
) |> hide_legend()


p <- highlight(
  p,
  on = "plotly_click",
  off = "plotly_doubleclick",
  #selectize = T, SHIFT+click emula la accion
  dynamic = T
)


p
```

```{r}

```

```{r}
ocup <- readxl::read_excel("data/eoh_ccaa.xlsx")
ocup
```

```{r}
ocup_nacional <- ocup |>
                 filter(LUGAR_RESIDENCIA == "Total") |>
                 select(AÑO, MES, CCAA, PERNOCTACIONES) |>
                 group_by(AÑO, MES) |>
                 summarise(pernoc=sum(PERNOCTACIONES, na.rm = TRUE), .groups = "drop")

ocup_nacional
```

```{r}
data <- ocup_nacional

data$Fecha <- as.Date(paste(data$AÑO, data$MES, "01", sep = "-"))


fig <- plot_ly(data, x = ~Fecha, y = ~pernoc, type = 'scatter', mode = 'lines', name = "Pernoctaciones", showlegend=F)

fig <- fig %>%
  add_trace(
    x = c(as.Date("2020-03-14"), as.Date("2020-03-14")),
    y = c(0, max(data$pernoc)),
    type = "scatter",
    mode = "lines",
    line = list(color = "red", dash = "solid"),
    name = "Mar 2020: Estado de alarma",
    showlegend = T
  ) %>%
  add_trace(
    x = c(as.Date("2020-06-21"), as.Date("2020-06-21")),
    y = c(0, max(data$pernoc)),
    type = "scatter",
    mode = "lines",
    line = list(color = "red", dash = "dash"),
    name = "Jun 2020: Fin del estado de alarma",
    showlegend = T
  ) %>%
  add_trace(
    x = c(as.Date("2020-10-25"), as.Date("2020-10-25")),
    y = c(0, max(data$pernoc)),
    type = "scatter",
    mode = "lines",
    line = list(color = "red", dash = "dot"),
    name = "Oct 2020: Nuevo estado de alarma",
    showlegend = T
  ) %>%

  add_trace(
    x = c(as.Date("2023-07-05"), as.Date("2023-07-05")),
    y = c(0, max(data$pernoc)),
    type = "scatter",
    mode = "lines",
    line = list(color = "red", dash = "dashdot"),
    name = "Jul 2023: Fin de la crisis sanitaria",
    showlegend = T
  ) %>%

  layout(
    title = "Evolución de la gestión de la crisis en España",
    xaxis = list(title = ""),
    yaxis = list(title = "Pernoctaciones",
                 range=c(0, 120e6)),
    legend = list(
      x = 0.01,
      y = 0.99,
      bgcolor = "rgba(255,255,255,0.7)",
      bordercolor = "black",
      borderwidth = 1,
      title = list(text = NULL)
    )
  ) |>
  rangeslider()


fig
```

```{r}
data_filtered <- ocup_nacional[ocup_nacional$AÑO < 2020, ]

ts_data <- ts(data_filtered$pernoc, start = c(1999, 1), frequency = 12)

modelo <- Arima(ts_data, order = c(1, 0, 2), seasonal = c(0, 1, 1), include.drift = TRUE)
```

```{r}
predicciones <- forecast(modelo, h = 42)
predicciones
```

```{r}


data1 <- data |> 
        filter(Fecha >= "2019-1-1", Fecha <= "2023-6-1")

pred <- data.frame(
  fecha = seq(from = as.Date("2020-01-01"), by = "month", length.out = 42),
  pernoc = predicciones$mean
)

inicio_covid <- as.Date("2020-03-01")
fin_covid <- as.Date("2021-12-01")

datos_covid <- datos_grafico[datos_grafico$fecha >= inicio_covid & datos_grafico$fecha <= fin_covid, ]

fig <- plot_ly() %>%
  add_lines(x = ~data1$Fecha, y = ~data1$pernoc, name = "Real", line = list(color = "blue")) %>%
  add_lines(x = ~pred$fecha, y = ~pred$pernoc, name = "Predicho", line = list(color = "red")) %>%
  add_ribbons(
    x = ~pred$fecha,
    ymin = ~pmin(data1$pernoc, pred$predicho),
    ymax = ~pmax(data1$pernoc, pred$predicho),
    fillcolor = "rgba(255, 0, 0, 0.2)", line = list(width = 0), name = "Pérdidas COVID"
  ) %>%
  layout(
    title = "Predicción ARIMA vs Valores Reales",
    xaxis = list(title = "Fecha"),
    yaxis = list(title = "Pernoctaciones"),
    legend = list(orientation = "h", y = -0.2)
  )

fig

```

```{r}

data1_filtrado <- data1 %>%
  filter(Fecha %in% pred$fecha)

datos_combinados <- merge(pred, data1_filtrado, by.x = "fecha", by.y = "Fecha", all.x = TRUE)


datos_combinados$ymin <- pmin(datos_combinados$pernoc.x, datos_combinados$pernoc.y, na.rm = TRUE)
datos_combinados$ymax <- pmax(datos_combinados$pernoc.x, datos_combinados$pernoc.y, na.rm = TRUE)


fig <- plot_ly() %>%
  add_lines(x = ~data1$Fecha, y = ~data1$pernoc, name = "Real", line = list(color = "blue")) %>%
  add_lines(x = ~pred$fecha, y = ~pred$pernoc, name = "Predicho", line = list(color = "red")) %>%
  add_ribbons(
    x = ~datos_combinados$fecha,
    ymin = ~datos_combinados$ymin,
    ymax = ~datos_combinados$ymax,
    fillcolor = "rgba(255, 0, 0, 0.2)", line = list(width = 0), name = "Pérdidas COVID"
  ) %>%
  layout(
    title = "Predicción ARIMA vs Valores Reales",
    xaxis = list(title = "Fecha"),
    yaxis = list(title = "Pernoctaciones"),
    legend = list(orientation = "h", y = -0.2)
  )

fig
```

## Pruebas

```{r}
p1 <- plot_ly() |>
     layout(
       title=list(
         text="Profit",
         x=0.5,
         y=0.95,
         xanchor="right",
         font=list(
           size=90
         )
       ),
       xaxis=list(
         showgrid=FALSE,
         zeroline=FALSE,
         showticklabels=FALSE
       ),
       yaxis=list(
         showgrid=FALSE,
         zeroline=FALSE,
         showticklabels=FALSE
       ),
       annotations = list(
         list(text = "76%", 
                       x = 0.12,
                       y = 0.5,
                       xref = "paper", 
                       yref = "paper",
                       showarrow = FALSE, 
                       font = list(size = 160,color = "lightgray")),
          list(text = "76%", 
                       x = 0.12,
                       y = 0,
                       xref = "paper", 
                       yref = "paper",
                       showarrow = FALSE, 
                       font = list(size = 50, color = "lightgreen"))
       )
      )


p2 <- mtcars |> plot_ly(x=~mpg) 

p1
```
